// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PushServerTest.Persistence;

namespace PushServerTest.Migrations
{
    [DbContext(typeof(PushServerDbContext))]
    partial class PushServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("PushServerTest.ApiClientData", b =>
                {
                    b.Property<string>("NodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("NodeId");

                    b.ToTable("ApiClientDatas");
                });

            modelBuilder.Entity("PushServerTest.UserData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiNodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("MessagesCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id", "ApiNodeId");

                    b.HasIndex("ApiNodeId");

                    b.ToTable("UserDatas");
                });

            modelBuilder.Entity("PushServerTest.UserData", b =>
                {
                    b.HasOne("PushServerTest.ApiClientData", null)
                        .WithMany()
                        .HasForeignKey("ApiNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
